from typing import Dict, Any
from app.services.parser_client import ProgramAnalysis

class CodegenGenerator:
    def generate_codegen(
        self, program_name: str, spec_data: Dict[str, Any], target_language: str = "python"
    ) -> Dict[str, str]:
        if target_language.lower() == "java":
            return self._generate_java_spring_boot(program_name, spec_data)
        return self.generate_python_stub_and_tests(program_name, spec_data)

    def generate_python_stub_and_tests(
        self, program_name: str, spec_data: Dict[str, Any]
    ) -> Dict[str, str]:
        pname_lower = program_name.lower()
        pname_upper = program_name.upper()

        summary = spec_data.get("summary", "Legacy migration stub")
        rules = spec_data.get("businessRules", [])
        inputs = spec_data.get("inputs", [])
        outputs = spec_data.get("outputs", [])
        edge_cases = spec_data.get("edgeCases", [])
        migration_notes = spec_data.get("migrationNotes", "")

        rules_doc = "\n".join([f"    - {r}" for r in rules]) or "    - Standard business rules"
        inputs_doc = "\n".join([f"    - {i}" for i in inputs]) or "    - Linkage parameters"
        outputs_doc = "\n".join([f"    - {o}" for o in outputs]) or "    - Result data structure"

        stub_code = f'''"""
{pname_upper} Legacy COBOL Migration Target Stub
==================================================
Summary: {summary}

Business Rules Encoded:
{rules_doc}

Inputs:
{inputs_doc}

Outputs:
{outputs_doc}

Migration Notes:
    {migration_notes}
"""

from typing import Dict, Any, Optional

class {pname_upper}Service:
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {{}}

    def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Executes business logic migrated from legacy COBOL program {pname_upper}.
        """
        # TODO: Implement migrated business logic
        # 1. Validate inputs
        # 2. Execute business rule calculations
        # 3. Format and return output record
        
        return {{
            "status": "SUCCESS",
            "message": "Migrated logic stub placeholder for {pname_upper}",
            "data": input_data
        }}
'''

        test_cases = []
        for idx, rule in enumerate(rules, start=1):
            func_name = f"test_rule_{idx}_" + "_".join(rule.split()[:4]).lower()
            func_name = "".join([c if c.isalnum() else "_" for c in func_name])
            test_cases.append(f'''@pytest.mark.skip(reason="Verification placeholder for rule: {rule}")
def {func_name}():
    service = {pname_upper}Service()
    # TODO: Supply test parameters and verify expected rule outcome
    assert True
''')

        for idx, edge in enumerate(edge_cases, start=1):
            func_name = f"test_edge_case_{idx}_" + "_".join(edge.split()[:4]).lower()
            func_name = "".join([c if c.isalnum() else "_" for c in func_name])
            test_cases.append(f'''@pytest.mark.skip(reason="Verification placeholder for edge case: {edge}")
def {func_name}():
    service = {pname_upper}Service()
    # TODO: Verify edge case handling
    assert True
''')

        test_code_body = "\n".join(test_cases) or '''@pytest.mark.skip(reason="Baseline migration placeholder")
def test_baseline_execution():
    service = ''' + pname_upper + '''Service()
    res = service.process({})
    assert res["status"] == "SUCCESS"
'''

        test_code = f'''import pytest
from {pname_lower}_stub import {pname_upper}Service

"""
Automated Pytest Suite for Migrated {pname_upper} Business Logic
Generated by Monolith Modernization Engine
"""

{test_code_body}
'''

        return {
            "stubFilename": f"{pname_lower}_stub.py",
            "stubCode": stub_code,
            "testFilename": f"test_{pname_lower}.py",
            "testCode": test_code,
            "language": "python"
        }

    def _generate_java_spring_boot(
        self, program_name: str, spec_data: Dict[str, Any]
    ) -> Dict[str, str]:
        pname = program_name.upper()
        pname_camel = pname[0].upper() + pname[1:].lower()

        summary = spec_data.get("summary", "Legacy migration service")
        rules = spec_data.get("businessRules", [])

        rules_comments = "\n".join([f" * - {r}" for r in rules])

        java_service = f'''package com.modern.migration.service;

import org.springframework.stereotype.Service;
import java.util.Map;
import java.util.HashMap;

/**
 * Migrated Java Spring Boot Service for legacy program {pname}.
 *
 * Summary:
 * {summary}
 *
 * Encoded Business Rules:
{rules_comments}
 */
@Service
public class {pname_camel}Service {{

    public Map<String, Object> execute(Map<String, Object> requestParams) {{
        Map<String, Object> response = new HashMap<>();
        
        // TODO: Implement migrated Java business logic
        response.put("status", "SUCCESS");
        response.put("program", "{pname}");
        response.put("data", requestParams);
        
        return response;
    }}
}}
'''

        java_test = f'''package com.modern.migration.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class {pname_camel}ServiceTest {{

    @Autowired
    private {pname_camel}Service service;

    @Test
    @Disabled("Migration test placeholder for {pname}")
    public void testExecuteBaseline() {{
        assertNotNull(service);
    }}
}}
'''

        return {
            "stubFilename": f"{pname_camel}Service.java",
            "stubCode": java_service,
            "testFilename": f"{pname_camel}ServiceTest.java",
            "testCode": java_test,
            "language": "java"
        }
